### ISSUE TITLE
DirectionsLanguage in german are not working

### ISSUE THREAD

**Issue by anoo4u** [Esri/arcgis-runtime-samples-dotnet#1]
DirectionsLanguage in German are not working , throws exception ...
 routeParams.DirectionsLanguage = new CultureInfo("de");

working for English ..
 routeParams.DirectionsLanguage = new CultureInfo("de");

**Comment by anttikajanus** [comment]
@rexhansen @mbranscomb Is this still relevant?

**Comment by rexhansen** [comment]
@anoo4u @anttikajanus @mbranscomb This was fixed in the latest release, 10.2.6.
