### ISSUE TITLE
Analyze Viewshed Sample

### ISSUE THREAD

**Issue by shehab-github** [Esri/arcgis-runtime-samples-dotnet#1083]
The GP service type is **Asynchronous**, however in the source code it's **SynchronousExecute** so it raises error.

https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/main/src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Geoprocessing/AnalyzeViewshed/AnalyzeViewshed.xaml.cs
**Line: 132,133**

**Comment by ZackAllen** [comment]
https://github.com/Esri/arcgis-runtime-samples-dotnet/pull/1085
PR is in with a fix. This will be fixed in `main` this week.

**Comment by shehab-github** [comment]
Great, Thanks.
