### ISSUE TITLE
MessageProcessingSample: need to document that installed SDK is required

### ISSUE THREAD

**Issue by garys-esri** [Esri/arcgis-runtime-samples-dotnet#112]
**Problem**

`MessageProcessingSample` is designed to display military symbols on the map, using MIL-STD-2525C. But an error message displays when **Process messages** is clicked:

> The Message could not be processed. MessageLayer must have been successfully loaded into a View (Map or Scene) before calling ProcessMessage.

Instead, the messages should display.

**Cause**

This sample requires the installed ArcGIS Runtime SDK for .NET. There are [directions to reference the installed SDK](https://github.com/Esri/arcgis-runtime-samples-dotnet#optional-change-references-to-use-the-installed-sdk-instead-of-nuget-package), but I can't find documentation in this repository that states which samples require the installed SDK. The key step is to delete the `arcgisruntime10.2.x` directory in `output\Desktop\Debug`.

**Possible Resolution**

Please add documentation somewhere to indicate the need for `MessageProcessingSample` to use the installed SDK.

**Comment by anttikajanus** [comment]
Hi Gary,
I'll have a look on this when I'm back from DevSummit.

**Comment by mbranscomb** [comment]
@garys-esri Use of military symbology in ArcGIS Runtime SDK for .NET no longer necessitates installation of the SDK.
