### ISSUE TITLE
using mvvm with isvisible for wmslayer and layers

### ISSUE THREAD

**Issue by MannusEtten** [Esri/arcgis-runtime-samples-dotnet#172]
i have a viewmodel with a boolean value to switch off/on layers (ShowFietsknooppunten)
in xaml i declare the binding but i tried a lot of opties but it doesn't work

IsVisible="{Binding DataContext.ShowFietsknooppunten, ElementName=mainscreen}"

mainscreen is the name of the usercontrol on which the mapview resides. This usercontrol datacontext is set to the viewmodel.

**Comment by mbranscomb** [comment]
@MannusEtten Please post questions regarding API usage in the [Forum](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net), thanks.
