### ISSUE TITLE
MapView.SetViewpoint doesn't work if called before MapView Loaded or SpatialReferenceChanged events have fired.

### ISSUE THREAD

**Issue by ThadT** [Esri/arcgis-runtime-samples-dotnet#183]
To set the view point before these events have fired, you can use Map.InitialViewpoint instead. Otherwise, handle the Loaded or SpatialReferenceChanged events to call SetViewpoint.
This is a placeholder to make sure workarounds are removed from the samples when the problem is fixed.

**Comment by mbranscomb** [comment]
Fixed in v100.0.
