### ISSUE TITLE
Failed to load local raster 

### ISSUE THREAD

**Issue by ddurgaprasad** [Esri/arcgis-runtime-samples-dotnet#184]
I am trying to load a tif file using below code.
``` 
    var myRaster_left = new Raster(@"C:\2015\11.tif");
    RasterLayer newRasterLayer_left = new Esri.ArcGISRuntime.Mapping.RasterLayer(myRaster_left);
     MyMapViewLeft.Map.OperationalLayers.Add(newRasterLayer_left);// adding raster
```
I get the error "An exception of type 'System.NullReferenceException' occurred in MilitaryApp.exe but was not handled in user code"

The file and path are absolutely fine and I am able to view in ArcGIS Desktop.However, runtime is unable to load the raster.Debugging shows variable  myRaster_left is set to null.

**Comment by mbranscomb** [comment]
@ddurgaprasad 

Please post any functional or SDK issues you run into in the beta forum: http://links.esri.com/runtime-dotnet-sdk-forum

Thanks
