### ISSUE TITLE
As Quartz Developer I expect identical SDK Object Model on Level of Data Access and Analysis for all platform specific Quartz SDKs. Where Do I find Attachments-API/Methods in Quarzt. NET?

### ISSUE THREAD

**Issue by RRieder** [Esri/arcgis-runtime-samples-dotnet#191]
As Quartz Developer I expect identical SDK Object Model on Level of Data Access and Analysis for all platform specific Quartz SDKs. Where Do I find Attachments-API/Methods in Quarzt. NET?

[QTdifferentObjects.docx](https://github.com/Esri/arcgis-runtime-samples-dotnet/files/414827/QTdifferentObjects.docx)

**Comment by anttikajanus** [comment]
Hi, thanks for the feedback.

The plan is to have full documentation and the same samples between all the Quartz SDKs but at the moment some teams are in a bit different situation compared to others. 

You can cast the feature to [ArcGISFeature](https://developers.arcgis.com/net/quartz/wpf/api-reference//html/T_Esri_ArcGISRuntime_Data_ArcGISFeature.htm) to get the attributes api visible. 

![image](https://cloud.githubusercontent.com/assets/1155333/17625333/4f51509e-60a0-11e6-87be-311a8a11d777.png)
