### ISSUE TITLE
How are relationships implemented in Quartz for .NET?

### ISSUE THREAD

**Issue by gisperg** [Esri/arcgis-runtime-samples-dotnet#192]
Hi!

How are relationships supported in Quartz (beta) for .NET for online FeatureServices/ ArcGISMapImageLayer and offline geodatabases ?

How can I generally acquire information about  relationship defintions from offline geodatabase tables and  feature services  ?
I cannot find anything that corresponds to the implementation in 
ArcGIS Runtime for .NET 10.2.7 (see images below), neither in the API, nor in the supplied ArcGISFeatureLayerInfo (ServiceInfo)

Thank you in advance.

ArcGIS Runtime for .NET 10.2.7:
![relationshipclassruntimedotnet1027](https://cloud.githubusercontent.com/assets/21099360/17768234/6887d352-6533-11e6-8e8b-f3190e517507.jpg)
![queryrelationshipruntimedotnet1027](https://cloud.githubusercontent.com/assets/21099360/17768244/7032af32-6533-11e6-87c7-608087037446.jpg)

**Comment by anttikajanus** [comment]
Hi,
At the moment working with related tables aren't supported in Quartz beta release. In beta, only way to get related records is to work directly against them using another table but this means that you need to know about the relationship in client. Supporting related records is going to be supported through the stack  (online - offline) later on. For more comments / discussion, please create issue to Beta forums.
