### ISSUE TITLE
Problem with TestFlight validation

### ISSUE THREAD

**Issue by spatialguy** [Esri/arcgis-runtime-samples-dotnet#238]
I am trying to use ArcGIS runtime nuget package in Xamarin iOS app. Once i add the NuGet package, build the app and publish it to TestFlight, I get the following errors. Does anyone have experience with this issue ?

ERROR ITMS-90086: "Missing 64-bit support. iOS apps submitted to the App Store must include 64-bit support and be built with the iOS 8 SDK or later. We recommend using the default "Standard Architectures" build setting for "Architectures" in Xcode, to build a single binary with both 32-bit and 64-bit support."

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file '/Frameworks/ArcGIS-arm64.framework/ArcGIS-arm64' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file '/Frameworks/ArcGIS-armv7.framework/ArcGIS-armv7' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

ERROR ITMS-90203: "Invalid architecture: Apps that include an app extension and framework must support arm64."

**Comment by zwaap** [comment]
@spatialguy there is a known issue with App Store submission for which there is a hotfix available.  See [this GeoNet thread](https://geonet.esri.com/thread/191038-xamarin-ios-compiler-and-build-settings) for further details.  Additionally, make sure that the supported architectures for your app includes ARM64.

In general, to report issues and ask for help, please post in the [ArcGIS Runtime SDK for .NET area of GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net).

**Comment by spatialguy** [comment]
Thank you very much and apologize for asking on wrong place.
