### ISSUE TITLE
WebTiledLayer's templateUri couldn't accept (row/col/leave) calculate

### ISSUE THREAD

**Issue by HTKing** [Esri/arcgis-runtime-samples-dotnet#286]
if there is any way to  achieve calculate (row/col/leave) in templateUri.
e.g.: WebTiledLayer tiledlayer= new WebTiledLayer("http://{subDomain}.com/x={col}&y={row/2+leave+1}&z={leave}");

**Comment by mbranscomb** [comment]
Hi,

This question would be better posted in the forum on Geonet - in fact there's already a response to a similar question and the same approach should work for your scenario as well: https://geonet.esri.com/thread/187238-how-do-i-add-an-wmts-layer.

Cheers
