### ISSUE TITLE
"sample-data" should be "samples-data".

### ISSUE THREAD

**Issue by mookrs** [Esri/arcgis-runtime-samples-dotnet#33]
In the section for Instructions of the README.md file, there is a little spelling mistake. Here is the sentence:

```
Place sample data contents in a folder named "sample-data" at the same level as the "src" folder for this repo.
````

If you make a folder named `sample-data` the project will never work, should be `samples-data`.

**Comment by katydalton** [comment]
Indeed! Apologies for the delay on that one @mookrs.
