### ISSUE TITLE
How can i use SketchOnMap Sample on Scene?

### ISSUE THREAD

**Issue by shaharbukra** [Esri/arcgis-runtime-samples-dotnet#332]
Hi,

What will be the right workaround to use it on the SceneView?
We want to sketch also on 3d :)

Thanks,
Shahar.

**Comment by mbranscomb** [comment]
@shaharbukra There is an old demo of editing on the SceneView written for the previous generation of the API: https://github.com/Esri/arcgis-runtime-demos-dotnet/tree/master/src/SceneViewEdit.

Currently you would need to follow a similar approach. The roadmap for ArcGIS Runtime SDK for .NET includes sketching in 3D for a future release.
