### ISSUE TITLE
Requested Changes with in GraphicsOverlay 

### ISSUE THREAD

**Issue by shaharbukra** [Esri/arcgis-runtime-samples-dotnet#367]
Hi there,

we have 2 problems using GraphicsOverlay,
- Its Sealed - meaning we cant extend it and add our own stuff in it. for example property Name  **Can it be change?**
- The Id property is not raising PropertyChange. **Any change to add PropertyChange into it?**

Thanks,
Shahar.

**Comment by dotMorten** [comment]
The ID is meant as an internal indexer for finding a overlay, not as a name in a ToC item.

I'd suggest you create a view model around your graphics overlays that accommodates the features you need for binding into your view, and allow you to do anything that provides model properties optimized for binding into a view.
Ie something along the lines of:

```
public class GraphicsOverlayCollectionViewModel : IEnumerable<GraphicsOverlayViewModel>
{
         public GraphicsOverlayCollectionViewModel(GraphicsOverlayCollection overlays)
         {
            // ...
         }
}
```

**Comment by dotMorten** [comment]
Feedback is noted though, but I'll close it here, as this repo is specific for the samples.
