### ISSUE TITLE
[Phone] Add sample using WebAuthenticationBroker with OAuth

### ISSUE THREAD

**Issue by rexhansen** [Esri/arcgis-runtime-samples-dotnet#4]
Add a sample that demonstrates how to use the recommended workflow for OAuth secured resources with Windows Phone 8.1 using WebAuthenticationBroker with IdentityManager in the ArcGIS Runtime SDK for .NET.   

Microsoft is promoting the use of WebAuthenticationBroker with OAuth workflows.  It's built into the ArcGIS Runtime SDK for .NET - Windows Store API.  It is not in the Windows Phone API due to complexity of implementation.   For sake of completeness we should include a sample.  Note, the current OAuth samples show use of web views.   

The WebAuthenticationBroker is limited by one issue, the domain in the authorize and approval urls must match.  If during the OAuth login process a user chooses to change the url (eg enter an organization subdomain) the WebAuthenticationBroker will not work.  The solution is either 1) use app logic to determine the organization url before the OAuth workflow starts or 2) Use a web view.     

For discussion and background details see: http://blogs.msdn.com/b/thunbrynt/archive/2014/04/14/windows-phone-8-1-for-developers-web-authentication-broker.aspx

**Comment by anttikajanus** [comment]
@rexhansen  @mbranscomb is this still relevant?

**Comment by rexhansen** [comment]
@anttikajanus @mbranscomb  Yes, this is still relevant. Microsoft is promoting the use of WebAuthenticationBroker with OAuth workflows.  It's built into the ArcGIS Runtime SDK for .NET - Windows Store API.  It is not in the Windows Phone API due to complexity of implementation.   For sake of completeness we should include a sample.  Note, the current OAuth samples show use of web views.   The WebAuthenticationBroker is limited by one issue, the domain in the authorize and approval url must match.  If during the OAuth login process a user chooses to change the url (eg enter an organization subdomain) the WebAuthenticationBroker will not work.  The solution is either 1) use app logic to determine the organization url before the OAuth workflow starts or 2) Use a web view.
