### ISSUE TITLE
Does not work with Android 4.2.2 and Xamarin

### ISSUE THREAD

**Issue by sandeepku** [Esri/arcgis-runtime-samples-dotnet#429]
We have been trying to put this sample on the Leica Zeno 20 UMTS having android Android 4.2.2.
Trying to open a simple "Display Map" page....gives this error. 
System.NotSupportedException: Could not activate JNI Handle 0x2b00025 (key_handle 0x4113f7e8) of Java type 'md525ae7a30145b6936c079fc7426298397/DisplayMap' as managed type 'ArcGISRuntimeXamarin.Samples.DisplayMap.DisplayMap'.

**Comment by mbranscomb** [comment]
Thanks for re-submitting to [Geonet](https://community.esri.com/thread/211621-arcgis-runtime-for-net-does-not-work-with-android-422).
