### ISSUE TITLE
Increase identify tolerance on XF FeatureLayerSelection sample

### ISSUE THREAD

**Issue by fragmer** [Esri/arcgis-runtime-samples-dotnet#505]
The tolerance on XF FeatureLayerSelection sample is a mere 5 pixels. This makes it difficult to actually select features — the features display as 24x24 pixel markers but only have  a tiny 10x10 tappable area at the center. Other platforms have it higher, e.g. at 14 for WPF: https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/e4f4085fe3207c79ec33efd7ca0f72d649519bcf/src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Layers/FeatureLayerSelection/FeatureLayerSelection.xaml.cs#L93-L94

**Comment by nCastle1** [comment]
This has already been addressed as part of the sample cartography updates.
