### ISSUE TITLE
Problems in XF "Preplanned map area" sample

### ISSUE THREAD

**Issue by fragmer** [Esri/arcgis-runtime-samples-dotnet#507]
I'm getting a warning pop-up after downloading "Municipal Center Area" in the XF "Download preplanned map areas" sample. After I close this warning, no features are drawn in the map.

![2018-07-17_20-25-48](https://user-images.githubusercontent.com/587809/42857648-9bdbbce4-89ff-11e8-9f58-ccb9f2803329.gif)

**Comment by nCastle1** [comment]
This sample needs to be completely re-evaluated to avoid some edge case issues. It was removed by the linked PR. An updated sample will be added in a PR coming soon.
