### ISSUE TITLE
Xamarin.Forms .NET Standard (old PCL) support?

### ISSUE THREAD

**Issue by jamesatgithub** [Esri/arcgis-runtime-samples-dotnet#516]
We have a existing Xamarin.Forms .NET Standard (shared class library) project and want to add ArcGIS feature to it, but found the sample and document all use "shared" project template. Could we use the runtime in a shared class library project?

**Comment by mbranscomb** [comment]
@jamesatgithub 
You can use ArcGIS Runtime in a Shared Project or a .NET Standard project (but not a PCL).

For a demo/example of .NET Standard use see: https://github.com/Esri/arcgis-runtime-demos-dotnet/tree/master/src/CampusRouting.

If you install the Visual Studio Extension from https://developers.arcgis.com/net/latest/ our VS project templates for Xamarin Forms include both Shared Project and .NET Standard options.
