### ISSUE TITLE
how to open local mdb(geodatabase) files in WPF

### ISSUE THREAD

**Issue by XiaoZhong233** [Esri/arcgis-runtime-samples-dotnet#544]
hello ,
i want to open local mdb file in my app.
i try to imitate the sample code.
but failed.
the error message report that there is no data.but i open it by arcgis desktop .it works
here is my code

``Geodatabase mobileGeodatabase = await Geodatabase.OpenAsync(file);
                        GeodatabaseFeatureTable featureTable = mobileGeodatabase.GeodatabaseFeatureTable("terlk_p");
                        await featureTable.LoadAsync();
                        FeatureLayer trailheadsFeatureLayer = new FeatureLayer(featureTable);
                        MyMapView.Map.OperationalLayers.Add(trailheadsFeatureLayer);
                        await MyMapView.SetViewpointGeometryAsync(trailheadsFeatureLayer.FullExtent);
``

**Comment by ThadT** [comment]
Hi @XiaoZhong233 
ArcGIS Runtime doesn't support direct reading of personal geodatabase (*.mdb) of file geodatabase (*.gdb). The geodatabase format for local data is a SQLite format database referred to as a "runtime geodatabase". You can create this kind of database using ArcGIS Desktop, as described in the [ArcMap help documentation](http://desktop.arcgis.com/en/arcmap/latest/map/working-with-arcmap/creating-arcgis-runtime-content.htm). There are other ways of working with local content too: such as taking a feature service offline, opening shapefiles, geopackages, etc. These options are described in some detail in the following ArcGIS Runtime SDK for .NET topics and samples:
 - [Create an offline layer](https://developers.arcgis.com/net/latest/wpf/guide/create-an-offline-layer.htm)
 - [Create an offline map](https://developers.arcgis.com/net/latest/wpf/guide/create-an-offline-map.htm)
 - [Synchronize offline edits](https://developers.arcgis.com/net/latest/wpf/sample-code/editandsyncfeatures.htm)
 - [GeoPackage](https://developers.arcgis.com/net/latest/wpf/sample-code/featurelayergeopackage.htm)
 - [Generate geodatabase](https://developers.arcgis.com/net/latest/wpf/sample-code/generategeodatabase.htm)

I hope that helps, please let me know if you have further questions! Thad (ttilton@esri.com)
