### ISSUE TITLE
Add offset to scenelayer 

### ISSUE THREAD

**Issue by saadat2930** [Esri/arcgis-runtime-samples-dotnet#578]
Hi! 
I dont know if this is the right place to open an issue here, as I am new to github. 
I recently started development of an app using Arcgis runtime dot net SDK (WPF). I have an issue related to the the elevation offset for scene layer package (slpk).
When i load my slpk layer to arcgis online it overlays above the ground. but in arcgis online i can set the elevation offset that corrects the vertical position of the model. 
Now if i use the portal item or arcgis online service in dot net WPF app it works fine because my model has been published with an offset.

but i want to load my slpk file local path, and i am unable to find any such option to set the offset value for ground overlay. 

```
Uri _serviceUri = new System.Uri(@"D:\Projects\test\lod75.slpk");
ArcGISSceneLayer sceneLayer = new ArcGISSceneLayer(_serviceUri);
myScene.OperationalLayers.Add(sceneLayer);

```

**Comment by rexhansen** [comment]
This is best answered in our GeoNet forums: https://community.esri.com/message/822170-setting-vertical-offset-for-slpk-layer-in-arcgis-runtime-net-sdk
