### ISSUE TITLE
Creation date in Sync Geodatabase sample gives GMT time instead of local time

### ISSUE THREAD

**Issue by mohi7253** [Esri/arcgis-runtime-samples-dotnet#59]
On creating new features in the local geodatabase, the creation time is in GMT. It would be helpful if the field name is "Date (in GMT)". Or if the sample is updated to display local time. 

https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/master/src/Desktop/ArcGISRuntimeSDKDotNet_DesktopSamples/Samples/Offline/SyncGeodatabase.xaml.cs

**Comment by anttikajanus** [comment]
@mbranscomb comment on this one?

**Comment by katydalton** [comment]
@anttikajanus - Thanks for pointing me to this thread: https://geonet.esri.com/thread/149334. Looks like the individual app/sample is responsible for accounting for differences between local/UTC time. We could  consider addressing this in v.Next of this sample.
