### ISSUE TITLE
Enhance InteractionOptions samples

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-runtime-samples-dotnet#62]
- Enhance MapView InteractionOptions sample
-  Add SceneView InteractionOptions sample 

Platforms for this issue:
- [ ] Desktop
- [ ] Store

**Comment by mbranscomb** [comment]
@anttikajanus I should be very grateful if you would code review the Pull Request associated with this issue. 

Cheers!

**Comment by anttikajanus** [comment]
@mbranscomb Looks good. Could you remove zoom box option from 3d and merge?

**Comment by mbranscomb** [comment]
@anttikajanus Updated Desktop PR (61) as per your feedback.
Created another PR (63) for Store for enhanced 2D and new 3D InteractionOptions samples.

**Comment by dotMorten** [comment]
FYI We are removing (hiding) SceneInteractionOptions for 10.2.6. More design to do and we're out of time.
