### ISSUE TITLE
No styles are specified

### ISSUE THREAD

**Issue by zhongshuiyuan** [Esri/arcgis-runtime-samples-dotnet#632]
when I use arcgis runtime sdk .NET to do Network Analysis , I got "No styles are specified",what is wrong, help me

**Comment by mbranscomb** [comment]
@zhongshuiyuan That error indicates the RouteParameters.DirectionsStyle property is not specified or invalid (https://developers.arcgis.com/net/latest/wpf/api-reference/html/P_Esri_ArcGISRuntime_Tasks_NetworkAnalysis_RouteParameters_DirectionsStyle.htm).

Note - this repo is for the sample code provided with ArcGIS Runtime SDK for .NET. For product questions please use [Geonet](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net).

**Comment by zhongshuiyuan** [comment]
No styles are specified errors when executing await RouteTaskCreateAsync. Before executing RouteTaskCreateAsync, it seems that DirectionsStyle can not be configured. If so, can you write detailed steps? I also asked questions in Geonet, but I haven't found a solution yet. Thank you very much.
