### ISSUE TITLE
No styles are specified

### ISSUE THREAD

**Issue by zhongshuiyuan** [Esri/arcgis-runtime-samples-dotnet#634]
No styles are specified errors when executing await RouteTaskCreateAsync. Before executing RouteTaskCreateAsync, it seems that DirectionsStyle can not be configured. If so, can Someone write detailed steps? 
![error](https://user-images.githubusercontent.com/8955999/56625932-1ec45900-6672-11e9-8198-82dc57520e60.png)

**Comment by nCastle1** [comment]
@zhongshuiyuan Apologies for the late response.

Can you please reply with information about the ArcGIS Server you're connecting to? This looks like it may be a server error.

Looking at the [service used in the samples](https://sampleserver6.arcgisonline.com/arcgis/rest/services/NetworkAnalysis/SanDiego/NAServer/Route), there are direction styles defined - `NA Desktop, NA Navigation, NA Campus `. Does the service page for your service look similar?

**Comment by zhongshuiyuan** [comment]
I got it, Thinks.
