### ISSUE TITLE
Unable to use Map after overlaying other controls on top 

### ISSUE THREAD

**Issue by apolloLegends** [Esri/arcgis-runtime-samples-dotnet#722]
User interaction with the map is ignored if other controls are overlaid on the map.  I.e.

`    <ContentPage.Content>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition></RowDefinition>
            </Grid.RowDefinitions>

            <Grid.ColumnDefinitions>
                <ColumnDefinition></ColumnDefinition>
            </Grid.ColumnDefinitions>

            <StackLayout VerticalOptions="FillAndExpand" Padding="10,10,10,10" Grid.Row="0" Grid.Column="0">
                <Label IsVisible="False"></Label>
                <forms:MapView x:Name="mapView" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"></forms:MapView>
            </StackLayout>

            <AbsoluteLayout Grid.Row="0" Grid.Column="0">
                <Entry AbsoluteLayout.LayoutBounds="15,15,300,30" Text="Search term"></Entry>
                <Button AbsoluteLayout.LayoutBounds="15,60,30,30" Text="GPS"></Button>
            </AbsoluteLayout>
        </Grid>
    </ContentPage.Content>`

On the code behind is a simple creation of a Map (new Map(Basemap.CreateDarkGrayCanvasVector());) and assignment to the MapView.

Commenting out the AbsoluteLayout block allows user interaction with the map.

Tested against both UWP and iOS.  I cant get this simple project to run on Android (Failed to initialize ArcGIS Runtime core.  The ArcGIS Runtime core library is inaccessible.').

Can someone offer a workaround other than moving the buttons elsewhere on the form so that they do not overlap?

Thanks.
[ESRIbug.zip](https://github.com/Esri/arcgis-runtime-samples-dotnet/files/3937104/ESRIbug.zip)

**Comment by nCastle1** [comment]
Hi @apolloLegends, I took a look at the project you shared and I think there are a few options to get this working. 

* If you set `InputTransparent="True"` and `CascadeInputTransparent="False"` on the AbsoluteLayout, the overlapping layout won't block user interaction while allowing the controls it contains to do so. In other words, that will get you the behavior you want. 
* Alternatively, a layout pattern I've seen used frequently, and which I know words well, is to set up a grid, with the MapView filling the grid and additional controls positioned using rows and columns. That approach is recommended for performance reasons - you can read more in the [performance docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/performance#choose-the-correct-layout)

As for the Android build, can you please confirm that the x86_64 build architecture is disabled and try again? When I tried to run the project you provided, I saw that x86_64 was selected and I was able to run on Android successfully after deselecting it.

To disable android build, right-click the Android project, select 'Properties', then deselect that build architecture under Advanced Android Options:

![devenv_GxAgCT8qsV](https://user-images.githubusercontent.com/29742178/70470530-0f1e4700-1a80-11ea-9a08-255b7b1050de.png)

**Comment by apolloLegends** [comment]
Hey @nCastle1, I appreciate the quick response and the suggested fixes.  I never gave consideration that the AbsoluteLayout would steal all input by default which obviously makes all underlying controls dormant.  Upon reflection this makes sense; and adopted your first suggestion.

As for the android issue sorry for the confusion, I didn't change the configuration for the submitted project (but did for my real project)., it turned out that my emulators had become corrupt and a quick factory reset fixed the issue for both 32 and 64bit API 28.  

However, as you have mentioned, the runtime only supports 32bit for Android,  Isn't this a problem as Google requires 64bit builds as of 1st August?
a. https://developer.android.com/distribute/best-practices/develop/64-bit
b. I've searched and I have yet to find any other question on this subject regarding the ESRI runtime

Cheers.

**Comment by nCastle1** [comment]
Hi @apolloLegends,

We do support Android for 64-bit ARM, but not x86_64. I do know that we've published the ArcGIS Runtime samples (in this case, native rather than .NET) to the Play Store and that happened after the 64-bit requirement came into effect. https://play.google.com/store/apps/details?id=com.esri.sampleviewer&hl=en_US

I don't know if its possible to publish x86 binaries to the store without the equivalent x86_64 binary. I've reached out to a colleague and will reply again when I know more.

**Comment by nCastle1** [comment]
I confirmed with the Android team that x86 support is intended only for use with the emulator. For publishing to the play store, we only support 32 and 64 bit ARM.

**Comment by apolloLegends** [comment]
Hey @nCastle1,

Thanks for the quick response.

It would seem this isn't as bad a deal as i originally thought, according to https://android.stackexchange.com/questions/186334/what-percentage-of-android-devices-runs-on-x86-architecture there's not a lot of x86 in play (~2% maybe).

Cheers.

**Comment by mbranscomb** [comment]
Support for x86_x64 architecture is now available when building for Android. 

https://developers.arcgis.com/net/reference/system-requirements/
> x86_64 - For targeting Android-supported devices with CPUs that support the Intel64 architecture (the instruction set commonly referred to as "x86-64").
