### ISSUE TITLE
Show Mouse Coordinates sample throws Exception

### ISSUE THREAD

**Issue by macca400** [Esri/arcgis-runtime-samples-dotnet#79]
On initial page load the Mapping > Show Mouse coordinates sample throws an unhanded exception until the MapView has finished initialization.

**Comment by macca400** [comment]
@katydalton Could you QA this please?
https://github.com/Esri/arcgis-runtime-samples-dotnet/pull/80

**Comment by katydalton** [comment]
@macca400 - Looks good for merge. Sorry for the delay; was out of town. Seems like a better way to do the initial null check, so does this need to happen on other samples eventually?
