### ISSUE TITLE
Cloned ArcGISMapImageSublayer with PictureMarkerSymbol not displayed

### ISSUE THREAD

**Issue by marhja** [Esri/arcgis-runtime-samples-dotnet#799]
Hi,

I've created a new ArcGISMapImageSublayer with points from an ArcGISMapImageLayer in a map package (.mpkx) by calling .Clone() on it and adding it to the ArcGISMapImageLayer.

Then I change the renderer of the cloned layer to a SimpleRenderer with a PictureMarkerSymbol, but nothing is displayed on the map and I get no exception.

The same renderer works for the original sublayer and for a FeatureLayer for same layer in the map package.

If I use a SimpleMarkerSymbol instead, the cloned layer is displayed.

Should it work with a PictureMarkerSymbol? I'm using 100.6 of both the .NET runtime and local server.

**Comment by ZackAllen** [comment]
Hi Markus. The workflow you are trying to do should work with PictureMarkerSymbols. Can you please share your code so that I can try to reproduce the issue on my end.
Also, for questions like this please post to [GeoNet](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net/content?filterID=contentstatus%5Bpublished%5D~objecttype~thread%5Bquestions%5D). Users and more of our staff will be able to see your question and offer help there.

Thanks, Zack

**Comment by marhja** [comment]
Hi ZackAllen,

further investigation have revealed that the cloning is not what's causing the problem, it's setting a DefinitionExpression on the sublayer.

I've used the Public_Art.shp from the [Aurora Colorado Shapefiles](https://www.arcgis.com/home/item.html?id=d98b3e5293834c5f852f13c569930caa) to create a Map Package Public_Art.mpk in ArcMap (didn't find a way to attach it here, so you'll have to create it).

Then I modified the Initialize() method in the _Local Server map image layer_ sample:

		private async void Initialize()
		{
			// Create a map and add it to the view
			MyMapView.Map = new Map(Basemap.CreateLightGrayCanvasVector());

			try
			{
				// LocalServer must not be running when setting the data path.
				if (LocalServer.Instance.Status == LocalServerStatus.Started)
				{
					await LocalServer.Instance.StopAsync();
				}

				// Set the local data path - must be done before starting. On most systems, this will be C:\EsriSamples\AppData.
				// This path should be kept short to avoid Windows path length limitations.
				string tempDataPathRoot = Directory.GetParent(Environment.GetFolderPath(Environment.SpecialFolder.Windows)).FullName;
				string tempDataPath = Path.Combine(tempDataPathRoot, "EsriSamples", "AppData");
				Directory.CreateDirectory(tempDataPath); // CreateDirectory won't overwrite if it already exists.

				LocalServer.Instance.AppDataPath = tempDataPath;

				// Start the local server instance
				await LocalServer.Instance.StartAsync();

				// Get the path to the map package that will be served
				//string datapath = GetDataPath();
				string datapath = @"<YOUR LOCAL FOLDER>\Public_Art.mpk";

				// Create the Map Service from the data
				_localMapService = new LocalMapService(datapath);

				// Start the feature service
				await _localMapService.StartAsync();

				// Get the url to the map service
				Uri myServiceUri = _localMapService.Url;

				// Create the layer from the url
				ArcGISMapImageLayer myImageLayer = new ArcGISMapImageLayer(myServiceUri);

				// Add the layer to the map
				MyMapView.Map.OperationalLayers.Add(myImageLayer);

				// Wait for the layer to load
				await myImageLayer.LoadAsync();

				// Set the viewpoint on the map to show the data
				MyMapView.SetViewpoint(new Viewpoint(myImageLayer.FullExtent));

				ArcGISMapImageSublayer subLayer = (ArcGISMapImageSublayer)myImageLayer.Sublayers[0];
				ArcGISMapImageSublayer clonedSubLayer = (ArcGISMapImageSublayer)subLayer.Clone();
				// The definition expression seems to be the problem, not the cloning.
				// Setting the definition expression on the non-cloned sublayer gives the same problem
				clonedSubLayer.DefinitionExpression = "ARTIST = 'Tom and Jean Latka'";
				subLayer.IsVisible = false;

				//clonedSubLayer.Renderer = CreateSimpleMarkerRenderer(); // WORKS
				clonedSubLayer.Renderer = CreatePictureMarkerRenderer();	// DOES NOT WORK

				myImageLayer.Sublayers.Insert(0, clonedSubLayer);
			}
			catch (Exception ex)
			{
				MessageBox.Show(string.Format("Please ensure that local server is installed prior to using the sample. See instructions in readme.md. Message: {0}", ex.Message), "Local Server failed to start");
			}
		}

and added two private methods (BlueRing.png for the PictureMarkerSymbol: ![BlueRing](https://user-images.githubusercontent.com/7138368/84677827-8d780c00-af2f-11ea-814e-ad81b1a5ad67.png))

		private SimpleRenderer CreateSimpleMarkerRenderer()
		{
			var simpleSymbol = new SimpleMarkerSymbol(SimpleMarkerSymbolStyle.Circle, Color.Orange, 10.0);
			var render = new SimpleRenderer(simpleSymbol);
			return render;
		}

		private SimpleRenderer CreatePictureMarkerRenderer()
		{
			string picturePath = @"<YOUR LOCAL FOLDER>\BlueRing.png";
			var pictureSymbol = new PictureMarkerSymbol(new System.Uri(picturePath))
			{ Width = 24, Height = 24 };

			var render = new SimpleRenderer(pictureSymbol);
			return render;
		}

I'll post to GeoNet next time, I ended up here because I was looking at these samples for a solution.

Thanks for your help,
/Markus

**Comment by marhja** [comment]
Upgraded to 100.8, now it works.

**Comment by mbranscomb** [comment]
@marhja Thanks for verifying.
