### ISSUE TITLE
Upgrade of samples to 100.9?

### ISSUE THREAD

**Issue by AllisonRob** [Esri/arcgis-runtime-samples-dotnet#824]
Hi there, 
I am interested to know when the samples will be upgraded to the 100.9 release of the Runtime .Net SDK .
Thanks for any insights on this, regards,
Allison

**Comment by ZackAllen** [comment]
Hi Allison. The current master branch of our repository uses the 100.9 ArcGIS Runtime packages in all of the solutions. Pulling from master will give you the latest samples.
For the sample viewer on the Microsoft App store, we will be releasing the 100.9.0 version in the near future.

Zack

**Comment by AllisonRob** [comment]
@ZackAllen
Thanks for your quick response Zack, and provided information. Sounds like exactly what I needed to know :)
Regards,
Allison
