### ISSUE TITLE
csproj still references 100.9 nuget packages

### ISSUE THREAD

**Issue by kirkktx** [Esri/arcgis-runtime-samples-dotnet#847]
This csproj still references 100.9
https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/7825b68abe113207b67a27cf02133af658a767d9/src/WPF/ArcGISRuntime.WPF.Viewer/ArcGISRuntime.WPF.Viewer.NetCore.csproj#L65

**Comment by ZackAllen** [comment]
Thank you for bringing this to our attention. A fix has been merged.
