### ISSUE TITLE
Exception for apikey more info link

### ISSUE THREAD

**Issue by kirkktx** [Esri/arcgis-runtime-samples-dotnet#848]
https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/7825b68abe113207b67a27cf02133af658a767d9/src/WPF/ArcGISRuntime.WPF.Viewer/ApiKeyPrompt.xaml.cs#L63
![image](https://user-images.githubusercontent.com/10727968/106164723-ebb8ce80-614f-11eb-93d9-e4217630125e.png)

**Comment by ZackAllen** [comment]
A fix has been merged. Thank you for reporting this 👍
