### ISSUE TITLE
How to check the AR functionality?

### ISSUE THREAD

**Issue by AmOfsi** [Esri/arcgis-runtime-samples-dotnet#859]
Hi, this could be a very stupid question, but when I run the program it pulls all the samples from the .Forms part of the solution and I have no clue as how to use/run the Forms.AR part of this code.

**Comment by ZackAllen** [comment]
Hi AmOfsi. You can use the AR samples with both the Android and iOS Xamarin.Forms sample viewers. We reference the Forms AR project in the [Forms Android .csproj file](https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/main/src/Forms/Android/ArcGISRuntime.Xamarin.Forms.Android.csproj#L174) and the [Forms iOS .csproj file](https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/main/src/Forms/iOS/ArcGISRuntime.Xamarin.Forms.iOS.csproj#L286).
If you are running on an AR compatible device, the samples should will up under the "Augmented reality" category.
We check for AR compatibility on Android using [this code.](https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/main/src/Forms/Shared/CategoryListPage.xaml.cs#L162-L181)
The AR toolkit is not available for UWP. These samples are not included for that viewer.

**Comment by AmOfsi** [comment]
Thank you so much, didn't realize that the UWP didn't support AR and had the wrong API on the emulator phone so it didn't support AR (hence it not appearing).

Cheers :)
