### ISSUE TITLE
Label not rotate when angle is not 0

### ISSUE THREAD

**Issue by GeoITwinkle** [Esri/arcgis-runtime-samples-dotnet#869]
I modified the code in the ShowLabelsOnLayer.xaml, but the label does not rotate with non-zero angle value, no matter positive or negative.
This also happens for point features in my other applications, changing the angle value does not work at all.
Please let me know if this is a bug or something else also needs configuration to make it work. 
Thanks!

![image](https://user-images.githubusercontent.com/8011074/113335686-4955cc80-92f3-11eb-94d7-a606036fccdd.png)

![image](https://user-images.githubusercontent.com/8011074/113335855-85892d00-92f3-11eb-96c1-e3513edc0674.png)

**Comment by nCastle1** [comment]
Hi @GeoITwinkle,

We've been looking into this internally. I don't have an answer to share right now, but I've notified the relevant team and they're investigating. I also shared your [Esri Community post](https://community.esri.com/t5/arcgis-runtime-sdk-for-net/bugs-in-label-and-symbology/m-p/1043287#M9938) with the team. Thank you for including the test project.

I'm hoping to share more in a few days. Thanks for your patience and thanks again for letting us know about the problem.

**Comment by GeoITwinkle** [comment]
> Hi @GeoITwinkle,
> 
> We've been looking into this internally. I don't have an answer to share right now, but I've notified the relevant team and they're investigating. I also shared your [Esri Community post](https://community.esri.com/t5/arcgis-runtime-sdk-for-net/bugs-in-label-and-symbology/m-p/1043287#M9938) with the team. Thank you for including the test project.
> 
> I'm hoping to share more in a few days. Thanks for your patience and thanks again for letting us know about the problem.

Thank you for your follow up. It is not urgent at the moment, but I think it is worth looking into. Thanks!

**Comment by nCastle1** [comment]
@GeoITwinkle I confirmed that ArcGIS Runtime currently does not support rotated labels for polygon features. I'll make a note internally to update the sample to make that clearer.

For point features, angles are supported but they need to be specified differently. The following shows an example label definition for point features:

```cs
        private const string LabelJson =
@"{
    ""labelExpressionInfo"":{""expression"":""'Label'""},
    ""labelAngleInfo"":
        {
            ""angleExpressionInfo"": {""expression"":""75"",""returnType"":""number""},
            ""rotationType"":""arithmetic""
        },
    ""textLayout"":""straight"",
    ""labelPlacement"":""esriServerPointLabelPlacementAboveRight"",
    ""symbol"":
        { 
            ""borderLineSize"":0,
            ""color"":[255,0,0,255],
            ""font"":
                {
                    ""decoration"":""none"",
                    ""size"":10,
                    ""style"":""normal"",
                    ""weight"":""normal""
                },
            ""horizontalAlignment"":""center"",
            ""type"":""esriTS"",
            ""verticalAlignment"":""middle"",
            ""xoffset"":0,
            ""yoffset"":0
        }
}";
```

Note that the `textLayout` field is required for label rotation to work in this case, and that `labelPlacement` must match the geometry type for the layer. [labelingInfo documentation](https://developers.arcgis.com/web-map-specification/objects/labelingInfo/) has a list of acceptable values.

**Comment by GeoITwinkle** [comment]
@nCastle1  Thanks Nathan. I will modify the code and see how it goes. 

By the way, there is no "LabelAngleInfo" or "textLayout" mentioned in the "labelingInfo documentation" webpage. Probably some kind of update is needed there. Otherwise developers will look into the Angle property of Text Symbol.

One more question: since Polygon feature is not supported for rotation, what about Polyline features?

Thanks.

**Comment by nCastle1** [comment]
@GeoITwinkle Thanks, I'll let the team know about the lack of documentation for those properties.

Angle rotation appears to work for polylines when using the point `labelPlacement` options:

```cs
private const string LabelJson =
@"{
    ""labelExpressionInfo"":{""expression"":""'Label'""},
    ""labelAngleInfo"":
        {
            ""angleExpressionInfo"": {""expression"":""10"",""returnType"":""number""},
            ""rotationType"":""arithmetic""
        },
    ""textLayout"":""straight"",
    ""labelPlacement"":""esriServerPointLabelPlacementAboveRight"",
    ""symbol"":
        { 
            ""borderLineSize"":0,
            ""color"":[255,0,0,255],
            ""font"":
                {
                    ""decoration"":""none"",
                    ""size"":10,
                    ""style"":""normal"",
                    ""weight"":""normal""
                },
            ""horizontalAlignment"":""center"",
            ""type"":""esriTS"",
            ""verticalAlignment"":""middle"",
            ""xoffset"":0,
            ""yoffset"":0
        }
}";
```

When using the line labelPlacement options (e.g. `esriServerLinePlacementBelowEnd`), the label is aligned with the polyline regardless of the specified angle.

Let me know if you have any other questions and I'll do my best to get them answered.

One more thing: I can't share full details yet, but there are changes to the API for labeling in Runtime planned for a future release. I recommend keeping an eye on [the blog](https://community.esri.com/t5/arcgis-runtime-sdks-blog/bg-p/arcgis-runtime-sdks-blog) for some exciting announcements.

**Comment by GeoITwinkle** [comment]
@nCastle1 Hi Nathan, I tried point and polyline features and they both work. Although the rotation is somehow interesting, it does not matter now. For future changes, I hope it can provide accessible classes/properties to configure instead of json, will keep an eye on the blog. Thanks again for your help!
