### ISSUE TITLE
File "SampleDescriptions.xml" not found

### ISSUE THREAD

**Issue by estercolero82** [Esri/arcgis-runtime-samples-dotnet#91]
In the Project "ArcGISRuntime.Samples.Desktop", the resource "Assets\SampleDescriptions.xml" is not found, and the main Project "ArcGISRuntime.Samples.DesktopViewer" uses the file to classify by category.

**Comment by katydalton** [comment]
@estercolero82 - That file should get automatically generated when you build the entire solution. Could you let me know if you're still having issues with the project not finding the file?

**Comment by estercolero82** [comment]
Hello Katy,

The problem was that I can't compile github compilation code, maybe because I'm using Visual Studio 2012 instead of 2013, so I have mode the code in a new project but forgot to include the automatic generation of the documentation file.

Now I can run the examples without problem. Thank you for your response.
