### ISSUE TITLE
Problem with Animate3DGraphic sample

### ISSUE THREAD

**Issue by victorfv** [Esri/arcgis-runtime-samples-dotnet#935]
Hello, I am testing the ArcGIS runtime for .NET Samples and I am having problems with the movement of the plane on the map, what could this be due to?

It happens to me from the Windows Store, and with the GitHub repository when compiling it with Visual Studio 2019
![imagen](https://user-images.githubusercontent.com/6042857/142158531-17597ec3-7bf8-4acc-b56f-d99613f641bc.png)

**Comment by nCastle1** [comment]
Hello,

I've noticed the number format is different from what I'm used to seeing, and I suspect that may have something to do with the issue.

Can you please share your Windows language and region settings?

Thank you!

**Comment by victorfv** [comment]
Thanks for you comment!

my configuration of Windows are this:
![imagen](https://user-images.githubusercontent.com/6042857/142370888-d20b7d82-ff1e-4243-adee-efc722fb483d.png)

Regards

**Comment by nCastle1** [comment]
Thank you for sharing that information. I was able to reproduce the issue, and have a PR up with a fix: https://github.com/Esri/arcgis-runtime-samples-dotnet/pull/937

**Comment by victorfv** [comment]
Hello guys,

the problem with Animate3DGraphics are solved, thanks for all!
![imagen](https://user-images.githubusercontent.com/6042857/142991916-75eb21bf-658a-4b9b-89a6-d2f1f1248afe.png)

**Comment by nCastle1** [comment]
Issue fix has been confirmed, closing.
